server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: lmx-service-provider
#swagger:
#  enabled: true
#  basePackage: com.lmx