server:
  port: 8081
spring:
  application:
    name: chapter5-hello-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true
