server:
  port: 9004
spring:
  application:
    name: chapter5-ribbon-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/